project:
  type: website

website:
  title: " "
  navbar:
    left:
      - href: about.qmd
        text: Home
      - href: timeline.qmd
        text: Time Line
      - href: research.qmd
        text: Research  
      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

